name: Lints

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cargo fmt
      run: cargo fmt --all -- --check

    - name: Cargo clippy
      run: cargo clippy --workspace -- -D warnings
    