name: Linux

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        set -ex
        sudo apt update
        sudo apt install pkg-config libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev -y

    - name: Build
      run: cargo test --verbose

    - name: Build
      run: cargo build --verbose --release
      if: startsWith(github.ref, 'refs/tags/')

    - name: Collect artifacts
      run: |
        set -ex
        mkdir gametest
        mv target/release/gametest gametest/
        mv assets gametest/
        zip Linux.zip -r gametest
      if: startsWith(github.ref, 'refs/tags/')

    - name: Upload artifact
      uses: svenstaro/upload-release-action@2.2.1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Linux.zip
        tag: ${{ github.ref }}
