name: MacOS

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo test --verbose

    - name: Build
      run: cargo build --verbose --release
      if: startsWith(github.ref, 'refs/tags/')

    - name: Collect artifacts
      run: |
        set -ex
        mkdir potat
        mv target/release/potat potat/
        mv assets potat/
        ls -lah potat/
        zip MacOS.zip -r potat
      if: startsWith(github.ref, 'refs/tags/')

    - name: Upload artifact
      uses: svenstaro/upload-release-action@2.2.1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: MacOS.zip
        tag: ${{ github.ref }}
